### ISSUE TITLE
Dependency on Asp.Net (Core)

### ISSUE THREAD

**Issue by AlanMacdonald** [mhusseini/Dryv#2]
Hi,

we looked at Dryv as the idea of writing server side validation and automatically getting the equivalent client side validation was attractive.  Our business logic lives in a separate project to the web site so we write our server validation on the input data transfer objects there.  However that means our business logic project takes a dependency on dryv (no problem) but that has a dependency on Asp.Net Core (problem).  Our business logic should be reusable outside of an Asp.Net website so taking a dependency on that is not what we want.

Ideally Dryv would have two separate packages - one for specifying the server side rules and performing validation and a second that can take the results of that validation and generate the client side script for Asp.Net Core.  If you had this design you could also support Asp.Net if you wanted as well maybe with the same first package for the server side.

Just thought I would pass on as this was a deal breaker for us and we have had to pass.

Thanks

**Comment by mhusseini** [comment]
Hi Alan,

thank you for this usefull suggestion. Breaking up the package seems like a reasonable thing to do and I will start implementing that on the weekend.

Best regards,
Munir

**Comment by mhusseini** [comment]
Hi Alan,

I have released a new version today. The core Dryv package is frontend agnostic and supports .NET Standard 1.2. There are separate packages for ASP.NET MVC 4.5.1 and ASP.NET Core now. Thanks again for your valuable input.

Best regards,
Munir
